services:
  app:
    build:
      context: .
      dockerfile: config/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py
