import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Switch, TextInput } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../theme';

export default function OptionsScreen({ user, onLogout, onUpdateUser }) {
  const [notifications, setNotifications] = useState(true);
  const [name, setName] = useState(user?.name || '');
  const [saved, setSaved] = useState(false);
  useEffect(() => { AsyncStorage.getItem('appSettings').then((raw) => { const settings = JSON.parse(raw || '{}'); if (settings.notifications !== undefined) setNotifications(settings.notifications); }); }, []);
  const updateNotifications = async (value) => { setNotifications(value); const settings = JSON.parse(await AsyncStorage.getItem('appSettings') || '{}'); await AsyncStorage.setItem('appSettings', JSON.stringify({ ...settings, notifications: value })); };
  const save = async () => { if (!name.trim()) return; await onUpdateUser({ ...user, name: name.trim() }); setSaved(true); setTimeout(() => setSaved(false), 1800); };

  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.title}>Settings</Text><Text style={styles.subtitle}>Control your local Quantum Swarm experience.</Text><View style={styles.section}><Text style={styles.sectionTitle}>Operator profile</Text><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{user?.name?.charAt(0)?.toUpperCase() || 'Q'}</Text></View><View style={{ flex: 1 }}><Text style={styles.label}>Display name</Text><TextInput value={name} onChangeText={setName} style={styles.input} /></View><TouchableOpacity style={styles.save} onPress={save}><Text style={styles.saveText}>{saved ? 'Saved' : 'Save'}</Text></TouchableOpacity></View><Text style={styles.email}>{user?.email || 'Local workspace mode'}</Text></View><View style={styles.section}><Text style={styles.sectionTitle}>Workspace preferences</Text><Setting icon="notifications-outline" title="Run notifications" copy="Notify when agents complete work or hit a blocker" right={<Switch value={notifications} onValueChange={updateNotifications} trackColor={{ false: colors.borderStrong, true: '#285894' }} thumbColor={notifications ? colors.primary : colors.textMuted} />} /><Setting icon="shield-checkmark-outline" title="Truthful quality status" copy="Projects only complete after tasks and quality gate pass" right={<Text style={styles.enforced}>Enforced</Text>} /><Setting icon="server-outline" title="API endpoint" copy="http://localhost:3001/api" /></View><View style={styles.section}><Text style={styles.sectionTitle}>Session</Text><TouchableOpacity style={styles.logout} onPress={onLogout}><Ionicons name="log-out-outline" size={18} color={colors.danger} /><Text style={styles.logoutText}>Log out</Text></TouchableOpacity></View></ScrollView>;
}
function Setting({ icon, title, copy, right }) { return <View style={styles.setting}><View style={styles.settingIcon}><Ionicons name={icon} size={19} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.settingTitle}>{title}</Text><Text style={styles.settingCopy}>{copy}</Text></View>{right}</View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.bg }, content: { padding: 24, maxWidth: 900, width: '100%', alignSelf: 'center' }, title: { color: colors.text, fontSize: 24, fontWeight: '800' }, subtitle: { color: colors.textMuted, fontSize: 13, marginTop: 5 }, section: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 10, padding: 16, marginTop: 20 }, sectionTitle: { color: colors.text, fontSize: 13, fontWeight: '800', marginBottom: 13 }, profile: { flexDirection: 'row', alignItems: 'flex-end' }, avatar: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.primarySoft, borderWidth: 1, borderColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginRight: 12 }, avatarText: { color: colors.text, fontSize: 17, fontWeight: '800' }, label: { color: colors.textMuted, fontSize: 10, marginBottom: 5 }, input: { height: 39, color: colors.text, backgroundColor: colors.bg, borderWidth: 1, borderColor: colors.border, borderRadius: 7, paddingHorizontal: 10, outlineStyle: 'none' }, save: { height: 39, justifyContent: 'center', backgroundColor: colors.primary, paddingHorizontal: 16, borderRadius: 7, marginLeft: 8 }, saveText: { color: '#fff', fontSize: 11, fontWeight: '800' }, email: { color: colors.textDim, fontSize: 10, marginTop: 10, marginLeft: 60 }, setting: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, borderTopWidth: 1, borderTopColor: colors.border }, settingIcon: { width: 38, height: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.primarySoft, marginRight: 11 }, settingTitle: { color: colors.text, fontSize: 12, fontWeight: '700' }, settingCopy: { color: colors.textMuted, fontSize: 10, marginTop: 4 }, enforced: { color: colors.success, fontSize: 10, fontWeight: '800' }, logout: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', borderWidth: 1, borderColor: '#58303a', borderRadius: 7, paddingHorizontal: 13, paddingVertical: 9 }, logoutText: { color: colors.danger, fontSize: 11, fontWeight: '800', marginLeft: 7 } });
